in: 
  thirumal:
    packageDao: com.enkindle.persistence.dao
    packageModel: com.enkindle.persistence.model
    rootFolder: erm2beans
    modelFolder: ${in.thirumal.rootFolder}/model
    daoFolder: ${in.thirumal.rootFolder}/dao
    