spring:
  profiles:
    active: DEV
    include: erm-target
  main: 
    allow-bean-definition-overriding: true
  datasource:
    jdbc-url: jdbc:postgresql://3.6.239.198:5432/payment
    url: ${spring.datasource.jdbc-url}
    username: postgres
    password: thirumal
  output:
    ansi:
      enabled: ALWAYS

name: erm-postgresql-sping-boot
server:
  port: 21991
  compression:
    enabled: true
  http2:
    enabled: true
  shutdown: graceful
logging:
  level:
    '[in.thirumal]': debug
    '[org.springframework]': debug
  file:
    path: logs
    name: logs/payment.log
  logback: 
    rollingpolicy: 
      max-history: 10
      max-file-size: 100MB
      total-size-cap: 1GB

#   
#springdoc:
#  version: '@springdoc.version@'
#  api-docs:
#    enabled: true
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html